all:
	python main.py

update:
	sudo apt-get install -f && sudo apt-get update && sudo apt-get upgrade && sudo apt-get

anaconda:
	wget http://repo.continuum.io/archive/Anaconda2-4.0.0-Linux-x86_64.sh && bash Anaconda2-4.0.0-Linux-x86_64.sh

conda-update:
	conda install scikit-learn && conda install pandas && conda install matplotlib && conda update --all